services:
  firebird-v5:
    image: firebirdsql/firebird:5
    environment:
      FIREBIRD_DATABASE: "database.fdb"
      FIREBIRD_ROOT_PASSWORD: "masterkey"
      FIREBIRD_USE_LEGACY_AUTH: "true"
    ports:
      - "3055:3050"

  firebird-v4:
    image: firebirdsql/firebird:4
    environment:
      FIREBIRD_DATABASE: "database.fdb"
      FIREBIRD_ROOT_PASSWORD: "masterkey"
      FIREBIRD_USE_LEGACY_AUTH: "true"
    ports:
      - "3054:3050"