<?php

namespace HarryGulliford\Firebird\Tests;

use Closure;
use HarryGulliford\Firebird\FirebirdConnection;
use Illuminate\Database\Schema\Blueprint;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase as BaseTestCase;

/**
 * Compiles schema SQL without a database connection.
 */
class SchemaGrammarTest extends BaseTestCase
{
    protected function compile(string $table, Closure $callback, bool $create = false, string $prefix = ''): array
    {
        $connection = new FirebirdConnection(fn () => null, 'database', $prefix);
        $connection->useDefaultSchemaGrammar();

        $blueprint = new Blueprint($connection, $table);

        if ($create) {
            $blueprint->create();
        }

        $callback($blueprint);

        return $blueprint->toSql();
    }

    #[Test]
    public function it_compiles_identity_primary_key_columns()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->id();
            $table->increments('counter')->startingValue(100);
        }, create: true);

        $this->assertSame([
            'create table "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, '
            .'"counter" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY NOT NULL)',
        ], $sql);
    }

    #[Test]
    public function it_compiles_identity_without_inline_primary_key_when_primary_command_exists()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->increments('id');
            $table->primary('id');
        }, create: true);

        $this->assertSame('create table "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL)', $sql[0]);
    }

    #[Test]
    public function it_compiles_column_modifiers_in_firebird_order()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->string('name')->charset('UTF8')->collation('UNICODE_CI')->default("O'Brien");
            $table->enum('status', ['a', "b'c"])->default('a');
            $table->timestamp('seen_at')->useCurrent();
            $table->string('note')->nullable();
        }, create: true);

        $this->assertSame([
            'create table "users" ('
            .'"name" VARCHAR(255) CHARACTER SET UTF8 DEFAULT \'O\'\'Brien\' NOT NULL COLLATE UNICODE_CI, '
            .'"status" VARCHAR(255) DEFAULT \'a\' NOT NULL CHECK ("status" IN (\'a\', \'b\'\'c\')), '
            .'"seen_at" TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL, '
            .'"note" VARCHAR(255))',
        ], $sql);
    }
}
