<?php

namespace HarryGulliford\Firebird\Tests;

use Closure;
use HarryGulliford\Firebird\FirebirdConnection;
use Illuminate\Database\Schema\Blueprint;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase as BaseTestCase;

/**
 * Compiles schema SQL without a database connection.
 */
class SchemaGrammarTest extends BaseTestCase
{
    protected function compile(string $table, Closure $callback, bool $create = false, string $prefix = ''): array
    {
        $connection = new FirebirdConnection(fn () => null, 'database', $prefix);
        $connection->useDefaultSchemaGrammar();

        $blueprint = new Blueprint($connection, $table);

        if ($create) {
            $blueprint->create();
        }

        $callback($blueprint);

        return $blueprint->toSql();
    }

    #[Test]
    public function it_compiles_identity_primary_key_columns()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->id();
            $table->increments('counter')->startingValue(100);
        }, create: true);

        $this->assertSame([
            'create table "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, '
            .'"counter" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY NOT NULL)',
        ], $sql);
    }

    #[Test]
    public function it_compiles_identity_without_inline_primary_key_when_primary_command_exists()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->increments('id');
            $table->primary('id');
        }, create: true);

        $this->assertSame('create table "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL)', $sql[0]);
    }

    #[Test]
    public function it_compiles_column_modifiers_in_firebird_order()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->string('name')->charset('UTF8')->collation('UNICODE_CI')->default("O'Brien");
            $table->enum('status', ['a', "b'c"])->default('a');
            $table->timestamp('seen_at')->useCurrent();
            $table->string('note')->nullable();
        }, create: true);

        $this->assertSame([
            'create table "users" ('
            .'"name" VARCHAR(255) CHARACTER SET UTF8 DEFAULT \'O\'\'Brien\' NOT NULL COLLATE UNICODE_CI, '
            .'"status" VARCHAR(255) DEFAULT \'a\' NOT NULL CHECK ("status" IN (\'a\', \'b\'\'c\')), '
            .'"seen_at" TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL, '
            .'"note" VARCHAR(255))',
        ], $sql);
    }

    #[Test]
    public function it_compiles_one_statement_per_added_column()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->string('a');
            $table->integer('b')->nullable();
        });

        $this->assertSame([
            'ALTER TABLE "users" ADD "a" VARCHAR(255) NOT NULL',
            'ALTER TABLE "users" ADD "b" INTEGER',
        ], $sql);
    }

    #[Test]
    public function it_compiles_drop_and_rename_commands()
    {
        $sql = $this->compile('users', function (Blueprint $table) {
            $table->dropUnique(['email']);
            $table->dropIndex(['name']);
            $table->dropColumn(['a', 'b']);
            $table->renameColumn('c', 'd');
            $table->dropPrimary();
        });

        $this->assertSame([
            'ALTER TABLE "users" DROP CONSTRAINT "users_email_unique"',
            'DROP INDEX "users_name_index"',
            'ALTER TABLE "users" DROP "a", DROP "b"',
            'ALTER TABLE "users" ALTER COLUMN "c" TO "d"',
            'execute block as declare c varchar(63); begin '
            .'select trim(rdb$constraint_name) from rdb$relation_constraints '
            .'where rdb$relation_name = \'users\' and rdb$constraint_type = \'PRIMARY KEY\' into :c; '
            .'execute statement \'ALTER TABLE "users" DROP CONSTRAINT "\' || c || \'"\'; end',
        ], $sql);
    }

    #[Test]
    public function it_throws_for_renaming_tables()
    {
        $this->expectException(\LogicException::class);

        $this->compile('users', fn (Blueprint $table) => $table->rename('people'));
    }

    #[Test]
    public function it_compiles_full_length_quoted_constraint_names()
    {
        $sql = $this->compile('a_rather_long_table_name', function (Blueprint $table) {
            $table->primary('id');
            $table->unique('another_long_column_name');
            $table->foreign('another_long_user_id')->references('id')->on('users');
            $table->dropForeign(['another_long_user_id']);
        });

        $this->assertSame([
            'ALTER TABLE "a_rather_long_table_name" ADD CONSTRAINT "a_rather_long_table_name_id_primary" PRIMARY KEY ("id")',
            'ALTER TABLE "a_rather_long_table_name" ADD CONSTRAINT "a_rather_long_table_name_another_long_column_name_unique" UNIQUE ("another_long_column_name")',
            'alter table "a_rather_long_table_name" add constraint "a_rather_long_table_name_another_long_user_id_foreign" foreign key ("another_long_user_id") references "users" ("id")',
            'ALTER TABLE "a_rather_long_table_name" DROP CONSTRAINT "a_rather_long_table_name_another_long_user_id_foreign"',
        ], $sql);
    }
}
