<?php

/**
 * Firebird Schema Grammar for Laravel.
 *
 * DDL support matrix (from parse.y analysis):
 *
 * CREATE TABLE:
 *   - Basic ........................ FB 1.0+
 *   - GLOBAL TEMPORARY TABLE ...... FB 2.1+ (ON COMMIT DELETE|PRESERVE ROWS)
 *   - IF NOT EXISTS ............... NOT SUPPORTED (use RECREATE TABLE for atomic drop+create)
 *   - COMPUTED BY (expr) .......... FB 1.0+ (Firebird-specific computed columns)
 *   - GENERATED ALWAYS AS (expr) .. FB 3.0+ (SQL standard computed columns)
 *   - GENERATED BY DEFAULT AS IDENTITY .. FB 3.0+ (auto-increment)
 *   - GENERATED ALWAYS AS IDENTITY ...... FB 3.0+ (strict auto-increment)
 *
 * ALTER TABLE:
 *   - ADD COLUMN .................. FB 1.0+
 *   - DROP COLUMN ................. FB 1.5+
 *   - ALTER COLUMN ... TO (rename) FB 1.0+
 *   - ALTER COLUMN ... TYPE ....... FB 1.0+
 *   - ALTER COLUMN SET/DROP NOT NULL FB 3.0+
 *   - ALTER COLUMN SET/DROP DEFAULT FB 1.0+
 *   - ALTER COLUMN SET GENERATED .. FB 3.0+
 *   - ALTER COLUMN DROP IDENTITY .. FB 3.0+
 *
 * DROP TABLE:
 *   - DROP TABLE .................. FB 1.0+
 *   - DROP TABLE IF EXISTS ........ NOT SUPPORTED (use EXECUTE BLOCK workaround)
 *   - RECREATE TABLE .............. FB 1.0+ (atomic drop+create)
 *
 * INDEXES:
 *   - CREATE INDEX ................ FB 1.0+
 *   - CREATE UNIQUE INDEX ......... FB 1.0+
 *   - CREATE DESC INDEX ........... FB 1.0+
 *   - Expression index (COMPUTED BY) FB 2.0+
 *   - Partial index (WHERE) ....... FB 5.0+
 *   - DROP INDEX .................. FB 1.0+
 *
 * SEQUENCES:
 *   - CREATE GENERATOR ............ FB 1.0+ (legacy)
 *   - CREATE SEQUENCE ............. FB 2.0+ (SQL standard)
 *   - GEN_ID(gen, n) .............. FB 1.0+ (all versions)
 *   - NEXT VALUE FOR .............. FB 2.0+
 *   - ALTER SEQUENCE RESTART ...... FB 2.0+
 *   - SET GENERATOR TO ............ FB 1.0+ (legacy)
 *
 * COMMENTS:
 *   - COMMENT ON TABLE/COLUMN ..... FB 2.0+
 *
 * IDENTIFIER LIMITS:
 *   - FB 2.5/3.0: 31 bytes max
 *   - FB 4.0+: 63 characters max (252 bytes UTF8)
 *
 * TYPE MAPPING (Dialect 3 assumed):
 *   - Dialect 1: DATE = TIMESTAMP, no TIME type, no BOOLEAN
 *   - Dialect 3: DATE = date-only, TIME available, BOOLEAN (FB 3.0+)
 *
 * Firebird DDL is transactional — $transactions = true.
 */

namespace HarryGulliford\Firebird\Schema\Grammars;

use HarryGulliford\Firebird\FirebirdConnection;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\Grammars\Grammar;
use Illuminate\Support\Fluent;

class FirebirdGrammar extends Grammar
{
    /**
     * Firebird supports DDL inside transactions (unlike MySQL).
     *
     * @var bool
     */
    protected $transactions = true;

    /**
     * Check if a feature is supported by the configured server version.
     */
    protected function supports(string $feature): bool
    {
        if ($this->connection instanceof FirebirdConnection) {
            return $this->connection->supportsFeature($feature);
        }

        return true;
    }

    /**
     * Get the max identifier length for the configured server version.
     */
    protected function maxIdentifierLength(): int
    {
        return $this->supports('long_identifiers') ? 63 : 31;
    }

    /**
     * Check if the connection uses Dialect 1.
     */
    protected function isDialect1(): bool
    {
        if ($this->connection instanceof FirebirdConnection) {
            return $this->connection->getDialect() === 1;
        }

        return false;
    }

    /**
     * Wrap a value in keyword identifiers.
     *
     * Dialect 1: no quoting (double-quotes = string literals).
     * Dialect 3: standard double-quote wrapping.
     */
    protected function wrapValue($value)
    {
        if ($value === '*') {
            return $value;
        }

        if ($this->isDialect1()) {
            return $value;
        }

        return '"'.str_replace('"', '""', $value).'"';
    }

    /**
     * The possible column modifiers.
     *
     * Order matters: Charset and Collate must come before Nullable/Default.
     * Increment (IDENTITY) must come last.
     *
     * @var array
     */
    protected $modifiers = ['Charset', 'Collate', 'Nullable', 'Default', 'GeneratedAs', 'Increment'];

    /**
     * The columns available as serials (auto-increment).
     *
     * @var array
     */
    protected $serials = ['bigInteger', 'integer', 'mediumInteger', 'smallInteger', 'tinyInteger'];

    // =========================================================================
    // INTROSPECTION QUERIES (RDB$ system tables)
    // =========================================================================

    /**
     * Compile the query to determine if the given table exists.
     *
     * @param  string|null  $schema
     * @param  string  $table
     * @return string
     */
    public function compileTableExists($schema, $table)
    {
        return sprintf(
            'select exists (select 1 from rdb$relations where rdb$relation_name = %s and rdb$relation_type = 0 and '
            .'(rdb$system_flag is null or rdb$system_flag = 0)) as "exists" from rdb$database',
            $this->quoteString($table),
        );
    }

    /**
     * Compile the query to determine the tables.
     *
     * Queries RDB$RELATIONS for user tables (system_flag = 0, relation_type = 0).
     * RDB$RELATION_NAME is CHAR(63) — needs TRIM.
     *
     * @param  string|string[]|null  $schema
     * @return string
     */
    public function compileTables($schema)
    {
        return 'select trim(trailing from rdb$relation_name) as "name" '
            .'from rdb$relations '
            .'where rdb$relation_type = 0 '
            .'and (rdb$system_flag is null or rdb$system_flag = 0) '
            .'order by rdb$relation_name';
    }

    /**
     * Compile the query to determine the views.
     *
     * Views have rdb$relation_type = 1 or rdb$view_blr IS NOT NULL.
     * rdb$view_source contains the SQL definition.
     *
     * @param  string|null  $schema
     * @return string
     */
    public function compileViews($schema)
    {
        return 'select trim(trailing from rdb$relation_name) as "name", '
            .'rdb$view_source as "definition" '
            .'from rdb$relations '
            .'where rdb$relation_type = 1 '
            .'and (rdb$system_flag is null or rdb$system_flag = 0) '
            .'order by rdb$relation_name';
    }

    /**
     * Compile the query to determine the columns.
     *
     * Full metadata query joining RDB$RELATION_FIELDS with RDB$FIELDS.
     *
     * Fields returned:
     *   - name: column name (trimmed)
     *   - field_type: Firebird internal type code (see Processor::mapFieldType)
     *   - field_sub_type: 0=binary, 1=text/numeric, 2=decimal
     *   - field_length: size in bytes
     *   - field_precision: NUMERIC/DECIMAL precision
     *   - field_scale: negative = decimal places
     *   - null_flag: 1=NOT NULL, NULL=nullable
     *   - default_source: DEFAULT clause as string (e.g. "DEFAULT 0")
     *   - computed_source: expression for COMPUTED BY columns
     *   - description: column comment (COMMENT ON COLUMN)
     *   - identity_type: not null if GENERATED AS IDENTITY (FB 3.0+)
     *   - collation_name: collation if set
     *
     * Note: identity_type column does not exist in RDB$ on FB 2.5 — query will
     * return NULL for it (the column exists in the SELECT but the field in
     * RDB$RELATION_FIELDS was added in FB 3.0).
     *
     * @param  string|null  $schema
     * @param  string  $table
     * @return string
     */
    public function compileColumns($schema, $table)
    {
        return sprintf(
            'select trim(rf.rdb$field_name) as "name", '
            .'f.rdb$field_type as "field_type", '
            .'f.rdb$field_sub_type as "field_sub_type", '
            .'f.rdb$field_length as "field_length", '
            .'f.rdb$field_precision as "field_precision", '
            .'f.rdb$field_scale as "field_scale", '
            .'rf.rdb$null_flag as "null_flag", '
            .'rf.rdb$default_source as "default_source", '
            .'f.rdb$computed_source as "computed_source", '
            .'rf.rdb$description as "description", '
            .'rf.rdb$identity_type as "identity_type", '
            .'(select trim(rc.rdb$collation_name) from rdb$collations rc '
            .'where rc.rdb$collation_id = rf.rdb$collation_id '
            .'and rc.rdb$character_set_id = f.rdb$character_set_id) as "collation_name" '
            .'from rdb$relation_fields rf '
            .'join rdb$fields f on rf.rdb$field_source = f.rdb$field_name '
            .'where rf.rdb$relation_name = %s '
            .'order by rf.rdb$field_position',
            $this->quoteString($table),
        );
    }

    /**
     * Compile the query to determine the list of columns.
     *
     * @deprecated Use compileColumns() instead.
     * @param  string  $table
     * @return string
     */
    public function compileColumnListing($table)
    {
        return "select trim(rdb\$field_name) as \"column_name\" from rdb\$relation_fields where rdb\$relation_name = '$table'";
    }

    /**
     * Compile the query to determine the indexes.
     *
     * Queries RDB$INDICES joined with RDB$INDEX_SEGMENTS.
     * Uses LIST() aggregate (FB 1.5+) to concatenate column names.
     * Checks RDB$RELATION_CONSTRAINTS for primary key detection.
     *
     * @param  string|null  $schema
     * @param  string  $table
     * @return string
     */
    public function compileIndexes($schema, $table)
    {
        return sprintf(
            'select trim(i.rdb$index_name) as "name", '
            .'i.rdb$unique_flag as "unique_flag", '
            .'(select case when rc.rdb$constraint_type = \'PRIMARY KEY\' then 1 else 0 end '
            .'from rdb$relation_constraints rc where rc.rdb$index_name = i.rdb$index_name) as "is_primary", '
            .'list(trim(sg.rdb$field_name), \',\') as "columns" '
            .'from rdb$indices i '
            .'join rdb$index_segments sg on sg.rdb$index_name = i.rdb$index_name '
            .'where i.rdb$relation_name = %s '
            .'and (i.rdb$system_flag is null or i.rdb$system_flag = 0) '
            .'group by i.rdb$index_name, i.rdb$unique_flag '
            .'order by i.rdb$index_name',
            $this->quoteString($table),
        );
    }

    /**
     * Compile the query to determine the foreign keys.
     *
     * Queries RDB$RELATION_CONSTRAINTS + RDB$REF_CONSTRAINTS for FK metadata.
     * Joins through to referenced table's index to get foreign columns.
     *
     * @param  string|null  $schema
     * @param  string  $table
     * @return string
     */
    public function compileForeignKeys($schema, $table)
    {
        return sprintf(
            'select trim(rc.rdb$constraint_name) as "name", '
            .'list(trim(sg.rdb$field_name), \',\') as "columns", '
            .'trim(i2.rdb$relation_name) as "foreign_table", '
            .'list(trim(sg2.rdb$field_name), \',\') as "foreign_columns", '
            .'trim(refc.rdb$update_rule) as "update_rule", '
            .'trim(refc.rdb$delete_rule) as "delete_rule" '
            .'from rdb$relation_constraints rc '
            .'join rdb$ref_constraints refc on refc.rdb$constraint_name = rc.rdb$constraint_name '
            .'join rdb$index_segments sg on sg.rdb$index_name = rc.rdb$index_name '
            .'join rdb$relation_constraints rc2 on rc2.rdb$constraint_name = refc.rdb$const_name_uq '
            .'join rdb$indices i2 on i2.rdb$index_name = rc2.rdb$index_name '
            .'join rdb$index_segments sg2 on sg2.rdb$index_name = rc2.rdb$index_name '
            .'and sg2.rdb$field_position = sg.rdb$field_position '
            .'where rc.rdb$relation_name = %s '
            .'and rc.rdb$constraint_type = \'FOREIGN KEY\' '
            .'group by rc.rdb$constraint_name, i2.rdb$relation_name, '
            .'refc.rdb$update_rule, refc.rdb$delete_rule '
            .'order by rc.rdb$constraint_name',
            $this->quoteString($table),
        );
    }

    // =========================================================================
    // DDL: CREATE / DROP / ALTER TABLE
    // =========================================================================

    /**
     * Compile a create table command.
     *
     * Firebird supports GLOBAL TEMPORARY TABLE (FB 2.1+) but not
     * local temporary tables or CREATE TABLE IF NOT EXISTS.
     * Use RECREATE TABLE for atomic drop-and-create (FB 1.0+).
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileCreate(Blueprint $blueprint, Fluent $command)
    {
        $columns = implode(', ', $this->getColumns($blueprint));

        if ($blueprint->temporary) {
            return 'create global temporary table '.$this->wrapTable($blueprint)
                ." ($columns) on commit preserve rows";
        }

        return 'create table '.$this->wrapTable($blueprint)." ($columns)";
    }

    /**
     * Compile a drop table command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDrop(Blueprint $blueprint, Fluent $command)
    {
        return 'drop table '.$this->wrapTable($blueprint);
    }

    /**
     * Compile a drop table (if exists) command.
     *
     * Firebird has NO DROP TABLE IF EXISTS syntax (any version).
     * Uses EXECUTE BLOCK to check RDB$RELATIONS first.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropIfExists(Blueprint $blueprint, Fluent $command)
    {
        return sprintf(
            'execute block as begin if (exists(select 1 from rdb$relations where rdb$relation_name = %s '
            .'and rdb$relation_type = 0 and (rdb$system_flag is null or rdb$system_flag = 0))) '
            .'then execute statement \'drop table %s\'; end',
            $this->quoteString($blueprint->getTable()),
            $this->wrapTable($blueprint)
        );
    }

    /**
     * Compile a column addition command.
     *
     * ALTER TABLE ... ADD [COLUMN] is supported since FB 1.0.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileAdd(Blueprint $blueprint, Fluent $command)
    {
        $table = $this->wrapTable($blueprint);
        $columns = $this->prefixArray('ADD', $this->getColumns($blueprint));

        return 'alter table '.$table.' '.implode(', ', $columns);
    }

    /**
     * Compile a change column command (alter column type).
     *
     * Firebird: ALTER TABLE t ALTER COLUMN col TYPE new_type (FB 1.0+).
     * FB 3.0+ also supports SET/DROP NOT NULL, SET/DROP DEFAULT.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileChange(Blueprint $blueprint, Fluent $command)
    {
        $table = $this->wrapTable($blueprint);
        $statements = [];

        foreach ($blueprint->getChangedColumns() as $column) {
            $type = $this->getType($column);
            $statements[] = sprintf('alter table %s alter column %s type %s',
                $table, $this->wrap($column->name), $type);
        }

        return implode('; ', $statements);
    }

    /**
     * Compile a rename column command.
     *
     * Firebird uses ALTER TABLE ... ALTER COLUMN old TO new (FB 1.0+).
     * NOT the standard RENAME COLUMN syntax.
     * Cannot rename columns that participate in constraints (PK, FK, UNIQUE, CHECK).
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileRenameColumn(Blueprint $blueprint, Fluent $command)
    {
        return sprintf('alter table %s alter column %s to %s',
            $this->wrapTable($blueprint),
            $this->wrap($command->from),
            $this->wrap($command->to)
        );
    }

    /**
     * Compile a drop column command.
     *
     * Firebird: ALTER TABLE t DROP col (FB 1.5+).
     * Supports dropping multiple columns in one statement.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropColumn(Blueprint $blueprint, Fluent $command)
    {
        $table = $this->wrapTable($blueprint);
        $columns = $this->prefixArray('drop', $this->wrapArray($command->columns));

        return 'alter table '.$table.' '.implode(', ', $columns);
    }

    // =========================================================================
    // DDL: CONSTRAINTS & INDEXES
    // =========================================================================

    /**
     * Compile a primary key command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compilePrimary(Blueprint $blueprint, Fluent $command)
    {
        $columns = $this->columnize($command->columns);

        return 'alter table '.$this->wrapTable($blueprint)." add primary key ({$columns})";
    }

    /**
     * Compile a unique key command.
     *
     * Index name truncated to 31 chars for FB 2.5/3.0 compatibility.
     * FB 4.0+ supports 63-char identifiers.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileUnique(Blueprint $blueprint, Fluent $command)
    {
        $table = $this->wrapTable($blueprint);
        $index = $this->wrap(substr($command->index, 0, $this->maxIdentifierLength()));
        $columns = $this->columnize($command->columns);

        return "alter table {$table} add constraint {$index} unique ({$columns})";
    }

    /**
     * Compile a plain index key command.
     *
     * Index name truncated to 31 chars for FB 2.5/3.0 compatibility.
     *
     * For expression indexes (FB 2.0+): CREATE INDEX idx ON t COMPUTED BY (expr)
     * For partial indexes (FB 5.0+): CREATE INDEX idx ON t (col) WHERE condition
     * — these are not handled here; use raw statements.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileIndex(Blueprint $blueprint, Fluent $command)
    {
        $columns = $this->columnize($command->columns);
        $index = $this->wrap(substr($command->index, 0, $this->maxIdentifierLength()));
        $table = $this->wrapTable($blueprint);

        return "create index {$index} on {$table} ({$columns})";
    }

    /**
     * Compile a foreign key command.
     *
     * FK name truncated to 31 chars for FB 2.5/3.0 compatibility.
     * ON DELETE/UPDATE actions: NO ACTION, CASCADE, SET DEFAULT, SET NULL.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileForeign(Blueprint $blueprint, Fluent $command)
    {
        $table = $this->wrapTable($blueprint);
        $on = $this->wrapTable($command->on);
        $columns = $this->columnize($command->columns);
        $onColumns = $this->columnize((array) $command->references);
        $fkName = substr($command->index, 0, $this->maxIdentifierLength());

        $sql = "alter table {$table} add constraint {$fkName} "
            ."foreign key ({$columns}) references {$on} ({$onColumns})";

        if (! is_null($command->onDelete)) {
            $sql .= " on delete {$command->onDelete}";
        }

        if (! is_null($command->onUpdate)) {
            $sql .= " on update {$command->onUpdate}";
        }

        return $sql;
    }

    /**
     * Compile a drop primary key command.
     *
     * Firebird requires constraint name to drop. Uses EXECUTE BLOCK to
     * look up the PK constraint name from RDB$RELATION_CONSTRAINTS.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropPrimary(Blueprint $blueprint, Fluent $command)
    {
        $table = $this->wrapTable($blueprint);
        $tableName = strtoupper($blueprint->getTable());

        return sprintf(
            'execute block as declare variable cname varchar(63); begin '
            .'select trim(rdb$constraint_name) from rdb$relation_constraints '
            .'where rdb$relation_name = \'%s\' and rdb$constraint_type = \'PRIMARY KEY\' '
            .'into :cname; '
            .'if (cname is not null) then execute statement '
            .'\'alter table %s drop constraint \' || cname; end',
            $tableName, $table
        );
    }

    /**
     * Compile a drop unique key command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropUnique(Blueprint $blueprint, Fluent $command)
    {
        return "alter table {$this->wrapTable($blueprint)} drop constraint {$command->index}";
    }

    /**
     * Compile a drop index command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropIndex(Blueprint $blueprint, Fluent $command)
    {
        return 'drop index '.$this->wrap($command->index);
    }

    /**
     * Compile a drop foreign key command.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileDropForeign(Blueprint $blueprint, Fluent $command)
    {
        return "alter table {$this->wrapTable($blueprint)} drop constraint {$command->index}";
    }

    // =========================================================================
    // DDL: SEQUENCES (for manual auto-increment management)
    // =========================================================================

    /**
     * Compile a create sequence statement.
     *
     * CREATE GENERATOR: FB 1.0+ (legacy)
     * CREATE SEQUENCE: FB 2.0+ (SQL standard)
     * START WITH / INCREMENT BY: FB 2.0+
     *
     * @param  string  $name
     * @param  int  $startWith
     * @param  int  $incrementBy
     * @return string
     */
    public function compileCreateSequence(string $name, int $startWith = 0, int $incrementBy = 1)
    {
        return "create sequence {$name} start with {$startWith} increment by {$incrementBy}";
    }

    /**
     * Compile a drop sequence statement.
     *
     * @param  string  $name
     * @return string
     */
    public function compileDropSequence(string $name)
    {
        return "drop sequence {$name}";
    }

    /**
     * Compile a restart sequence statement.
     *
     * ALTER SEQUENCE RESTART: FB 2.0+
     * SET GENERATOR TO: FB 1.0+ (legacy, use for FB 2.5 compat)
     *
     * @param  string  $name
     * @param  int  $value
     * @return string
     */
    public function compileRestartSequence(string $name, int $value = 0)
    {
        return "alter sequence {$name} restart with {$value}";
    }

    // =========================================================================
    // DDL: COMMENTS
    // =========================================================================

    /**
     * Compile a table comment command.
     *
     * COMMENT ON TABLE: FB 2.0+
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileTableComment(Blueprint $blueprint, Fluent $command)
    {
        return sprintf('comment on table %s is %s',
            $this->wrapTable($blueprint),
            $this->quoteString($command->comment)
        );
    }

    /**
     * Compile a column comment command.
     *
     * COMMENT ON COLUMN: FB 2.0+
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $command
     * @return string
     */
    public function compileComment(Blueprint $blueprint, Fluent $command)
    {
        $comments = [];

        foreach ($blueprint->getChangedColumns() as $column) {
            if (isset($column->comment)) {
                $comments[] = sprintf('comment on column %s.%s is %s',
                    $this->wrapTable($blueprint),
                    $this->wrap($column->name),
                    $this->quoteString($column->comment)
                );
            }
        }

        return implode('; ', $comments);
    }

    // =========================================================================
    // COLUMN MODIFIERS
    // =========================================================================

    /**
     * Get the SQL for a character set column modifier.
     *
     * CHARACTER SET: all versions.
     * Common charsets: UTF8, ISO8859_1, WIN1252, NONE
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyCharset(Blueprint $blueprint, Fluent $column)
    {
        if (! is_null($column->charset)) {
            return ' character set '.$column->charset;
        }
    }

    /**
     * Get the SQL for a collation column modifier.
     *
     * COLLATE: all versions.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyCollate(Blueprint $blueprint, Fluent $column)
    {
        if (! is_null($column->collation)) {
            return ' collate '.$column->collation;
        }
    }

    /**
     * Get the SQL for a nullable column modifier.
     *
     * NOT NULL: all versions.
     * ALTER COLUMN SET/DROP NOT NULL: FB 3.0+ only.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyNullable(Blueprint $blueprint, Fluent $column)
    {
        return $column->nullable ? '' : ' not null';
    }

    /**
     * Get the SQL for a default column modifier.
     *
     * DEFAULT: all versions.
     * CURRENT_TIMESTAMP, CURRENT_DATE, CURRENT_TIME: all versions.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyDefault(Blueprint $blueprint, Fluent $column)
    {
        if (! is_null($column->default)) {
            return ' default '.$this->getDefaultValue($column->default);
        }
    }

    /**
     * Get the SQL for a computed column modifier.
     *
     * COMPUTED BY (expr): FB 1.0+ (Firebird-specific)
     * GENERATED ALWAYS AS (expr): FB 3.0+ (SQL standard)
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyGeneratedAs(Blueprint $blueprint, Fluent $column)
    {
        if (! is_null($column->virtualAs)) {
            return ' computed by ('.$column->virtualAs.')';
        }

        if (! is_null($column->storedAs)) {
            return ' computed by ('.$column->storedAs.')';
        }
    }

    /**
     * Get the SQL for an auto-increment column modifier.
     *
     * GENERATED BY DEFAULT AS IDENTITY: FB 3.0+ only.
     * GENERATED ALWAYS AS IDENTITY: FB 3.0+ (strict, no manual values).
     *
     * For FB 2.5: use CREATE GENERATOR + TRIGGER manually, or
     * application-level GEN_ID() in Eloquent model creating() event.
     *
     * @param  \Illuminate\Database\Schema\Blueprint  $blueprint
     * @param  \Illuminate\Support\Fluent  $column
     * @return string|null
     */
    protected function modifyIncrement(Blueprint $blueprint, Fluent $column)
    {
        if (in_array($column->type, $this->serials) && $column->autoIncrement) {
            if (! $this->supports('identity')) {
                // FB 2.5: no IDENTITY columns. Consumer must use GEN_ID()
                // in model creating() event or trigger + generator.
                return '';
            }

            return ' generated by default as identity';
        }
    }

    // =========================================================================
    // COLUMN TYPE MAPPINGS
    // =========================================================================

    /**
     * Create the column definition for a char type.
     *
     * CHAR(n): all versions. Max 32767 bytes.
     */
    protected function typeChar(Fluent $column)
    {
        return "char({$column->length})";
    }

    /**
     * Create the column definition for a string type.
     *
     * VARCHAR(n): all versions. Max 32765 bytes.
     */
    protected function typeString(Fluent $column)
    {
        return "varchar({$column->length})";
    }

    /**
     * Create the column definition for a tiny text type.
     *
     * No equivalent in Firebird — maps to BLOB SUB_TYPE TEXT.
     */
    protected function typeTinyText(Fluent $column)
    {
        return 'blob sub_type text';
    }

    /**
     * Create the column definition for a text type.
     *
     * BLOB SUB_TYPE TEXT (CLOB equivalent): all versions.
     */
    protected function typeText(Fluent $column)
    {
        return 'blob sub_type text';
    }

    /** @see typeText */
    protected function typeMediumText(Fluent $column)
    {
        return 'blob sub_type text';
    }

    /** @see typeText */
    protected function typeLongText(Fluent $column)
    {
        return 'blob sub_type text';
    }

    /**
     * INTEGER: all versions (32-bit).
     */
    protected function typeInteger(Fluent $column)
    {
        return 'integer';
    }

    /**
     * BIGINT: all versions (64-bit).
     */
    protected function typeBigInteger(Fluent $column)
    {
        return 'bigint';
    }

    /**
     * No MEDIUMINT in Firebird — maps to INTEGER.
     */
    protected function typeMediumInteger(Fluent $column)
    {
        return 'integer';
    }

    /**
     * SMALLINT: all versions (16-bit, -32768 to 32767).
     */
    protected function typeTinyInteger(Fluent $column)
    {
        return 'smallint';
    }

    /** @see typeTinyInteger */
    protected function typeSmallInteger(Fluent $column)
    {
        return 'smallint';
    }

    /**
     * FLOAT: all versions (32-bit IEEE 754).
     */
    protected function typeFloat(Fluent $column)
    {
        return 'float';
    }

    /**
     * DOUBLE PRECISION: all versions (64-bit IEEE 754).
     */
    protected function typeDouble(Fluent $column)
    {
        return 'double precision';
    }

    /**
     * DECIMAL(total, places): all versions.
     * Precision up to 18 on FB 2.5/3.0, up to 38 on FB 4.0+.
     */
    protected function typeDecimal(Fluent $column)
    {
        return "decimal({$column->total}, {$column->places})";
    }

    /**
     * Boolean type.
     *
     * FB 3.0+ Dialect 3: native BOOLEAN (TRUE/FALSE/UNKNOWN)
     * FB 2.5 / Dialect 1: no native boolean — use SMALLINT with CHECK
     *
     * Currently maps to SMALLINT for maximum compatibility.
     * Override in a version-aware grammar for native BOOLEAN on FB 3.0+.
     */
    protected function typeBoolean(Fluent $column)
    {
        return $this->supports('boolean') ? 'boolean' : 'smallint';
    }

    /**
     * Enum type.
     *
     * Firebird has no ENUM type. Emulated with VARCHAR + CHECK constraint.
     */
    protected function typeEnum(Fluent $column)
    {
        $allowed = array_map(fn($a) => "'".$a."'", $column->allowed);

        return "varchar(255) check (\"{$column->name}\" in (".implode(', ', $allowed).'))';
    }

    /**
     * JSON type.
     *
     * Firebird has no native JSON type. Uses VARCHAR(8191) as workaround.
     * For larger JSON, consider BLOB SUB_TYPE TEXT.
     */
    protected function typeJson(Fluent $column)
    {
        return 'blob sub_type text';
    }

    /**
     * JSONB type.
     *
     * Same as JSON — Firebird has no binary JSON format.
     */
    protected function typeJsonb(Fluent $column)
    {
        return 'blob sub_type text';
    }

    /**
     * DATE type.
     *
     * Dialect 3: date-only (no time component).
     * Dialect 1: DATE includes time (acts as TIMESTAMP) — be aware!
     */
    protected function typeDate(Fluent $column)
    {
        return 'date';
    }

    /**
     * TIMESTAMP: all versions.
     */
    protected function typeDateTime(Fluent $column)
    {
        return 'timestamp';
    }

    /**
     * TIMESTAMP WITH TIME ZONE: FB 4.0+ only.
     * Falls back to plain TIMESTAMP on older versions.
     */
    protected function typeDateTimeTz(Fluent $column)
    {
        return $this->supports('tz_types') ? 'timestamp with time zone' : 'timestamp';
    }

    /**
     * TIME: Dialect 3 only (does not exist in Dialect 1).
     */
    protected function typeTime(Fluent $column)
    {
        return 'time';
    }

    /**
     * TIME WITH TIME ZONE: FB 4.0+ only.
     * Falls back to plain TIME on older versions.
     */
    protected function typeTimeTz(Fluent $column)
    {
        return $this->supports('tz_types') ? 'time with time zone' : 'time';
    }

    /**
     * TIMESTAMP: all versions.
     */
    protected function typeTimestamp(Fluent $column)
    {
        if ($column->useCurrent) {
            return 'timestamp default current_timestamp';
        }

        return 'timestamp';
    }

    /** @see typeDateTimeTz */
    protected function typeTimestampTz(Fluent $column)
    {
        return $this->supports('tz_types') ? 'timestamp with time zone' : $this->typeTimestamp($column);
    }

    /**
     * YEAR type — no equivalent in Firebird. Maps to SMALLINT.
     */
    protected function typeYear(Fluent $column)
    {
        return 'smallint';
    }

    /**
     * BLOB SUB_TYPE BINARY: all versions.
     */
    protected function typeBinary(Fluent $column)
    {
        return 'blob sub_type binary';
    }

    /**
     * UUID — CHAR(36): all versions.
     */
    protected function typeUuid(Fluent $column)
    {
        return 'char(36)';
    }

    /**
     * IP address — VARCHAR(45): all versions (supports IPv4 and IPv6).
     */
    protected function typeIpAddress(Fluent $column)
    {
        return 'varchar(45)';
    }

    /**
     * MAC address — VARCHAR(17): all versions.
     */
    protected function typeMacAddress(Fluent $column)
    {
        return 'varchar(17)';
    }
}
