<?php

/**
 * Firebird Connection for Laravel.
 *
 * Version-aware connection. Capabilities are determined from the config
 * array (no runtime auto-detect, no chicken-and-egg with grammar).
 *
 * Config keys used for capability detection:
 *   'server_version' => 2|3|4|5  (Firebird major version, default: 3)
 *
 * Feature availability by server version:
 *   FB 2.5: FIRST/SKIP, GEN_ID, stored procedures, CONTAINING, UPDATE OR INSERT
 *   FB 3.0: FETCH FIRST, BOOLEAN, IDENTITY columns, window functions, OFFSET/ROWS
 *   FB 4.0: LATERAL JOIN, INT128, DECFLOAT, TZ types, named windows, LAG/LEAD
 *   FB 5.0: SKIP LOCKED, partial indexes, MERGE RETURNING, scrollable cursors
 *
 * SQL Dialect (property of the .fdb file):
 *   Dialect 1: InterBase legacy — DATE includes time, "" = string literal, no BOOLEAN, no TIME
 *   Dialect 3: Modern — DATE = date-only, "" = identifier, BOOLEAN (FB 3.0+), TIME available
 *   Set via 'dialect' => 1|3 in config (also passed to DSN by connector).
 */

namespace HarryGulliford\Firebird;

use HarryGulliford\Firebird\Query\Builder as FirebirdQueryBuilder;
use HarryGulliford\Firebird\Query\Grammars\FirebirdGrammar as FirebirdQueryGrammar;
use HarryGulliford\Firebird\Query\Processors\FirebirdProcessor as FirebirdQueryProcessor;
use HarryGulliford\Firebird\Schema\Builder as FirebirdSchemaBuilder;
use HarryGulliford\Firebird\Schema\Grammars\FirebirdGrammar as FirebirdSchemaGrammar;
use Illuminate\Database\Connection as DatabaseConnection;
use Illuminate\Support\Str;
use PDO;

class FirebirdConnection extends DatabaseConnection
{
    /**
     * {@inheritDoc}
     */
    public function getDriverTitle()
    {
        return 'Firebird';
    }

    /**
     * Get the configured server major version.
     *
     * Read from config 'server_version'. Defaults to 3 (modern).
     * Set to 2 for Firebird 2.5 legacy servers.
     *
     *   'server_version' => 2  →  FIRST/SKIP, no IDENTITY, no BOOLEAN
     *   'server_version' => 3  →  FETCH FIRST, IDENTITY, BOOLEAN (default)
     *   'server_version' => 4  →  LATERAL, TZ types, 63-char identifiers
     *   'server_version' => 5  →  SKIP LOCKED, partial indexes
     *
     * @return int
     */
    public function getServerMajorVersion(): int
    {
        return (int) ($this->getConfig('server_version') ?? 3);
    }

    /**
     * Get the configured SQL dialect.
     *
     * Read from config 'dialect'. Defaults to 3 (modern).
     *
     *   'dialect' => 1  →  DATE=TIMESTAMP, no TIME, "" = string literal
     *   'dialect' => 3  →  DATE=date-only, TIME available, "" = identifier
     *
     * @return int
     */
    public function getDialect(): int
    {
        return (int) ($this->getConfig('dialect') ?? 3);
    }

    /**
     * Check if a feature is supported by the configured server version.
     *
     * @param  string  $feature
     * @return bool
     */
    public function supportsFeature(string $feature): bool
    {
        $v = $this->getServerMajorVersion();

        return match ($feature) {
            'fetch_first'       => $v >= 3, // OFFSET/FETCH syntax
            'first_skip'        => true,    // FIRST/SKIP works on all versions
            'boolean'           => $v >= 3, // native BOOLEAN type
            'identity'          => $v >= 3, // GENERATED BY DEFAULT AS IDENTITY
            'lateral'           => $v >= 4, // LATERAL derived tables
            'tz_types'          => $v >= 4, // TIMESTAMP/TIME WITH TIME ZONE
            'long_identifiers'  => $v >= 4, // 63 chars vs 31 bytes
            'skip_locked'       => $v >= 5, // WITH LOCK SKIP LOCKED
            'partial_index'     => $v >= 5, // CREATE INDEX ... WHERE
            'merge_returning'   => $v >= 5, // MERGE ... RETURNING
            'window_functions'  => $v >= 3, // ROW_NUMBER, RANK, etc.
            'exists_function'   => $v >= 3, // SELECT EXISTS(...) as scalar
            default => true,
        };
    }

    /**
     * Get the server version for the connection (queries the server).
     *
     * @return string  e.g. "5.0.2"
     */
    public function getServerVersion(): string
    {
        $version = $this->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION);

        return Str::match('/\(remote server\), version "\w+-V(\d+\.\d+\.\d+)/', $version);
    }

    /**
     * Get the default query grammar instance.
     */
    protected function getDefaultQueryGrammar()
    {
        return new FirebirdQueryGrammar($this);
    }

    /**
     * Get the default post processor instance.
     */
    protected function getDefaultPostProcessor()
    {
        return new FirebirdQueryProcessor;
    }

    /**
     * Get a schema builder instance for the connection.
     */
    public function getSchemaBuilder()
    {
        if (is_null($this->schemaGrammar)) {
            $this->useDefaultSchemaGrammar();
        }

        return new FirebirdSchemaBuilder($this);
    }

    /**
     * Get the default schema grammar instance.
     */
    protected function getDefaultSchemaGrammar()
    {
        return new FirebirdSchemaGrammar($this);
    }

    /**
     * Get a new query builder instance.
     */
    public function query()
    {
        return new FirebirdQueryBuilder(
            $this, $this->getQueryGrammar(), $this->getPostProcessor()
        );
    }

    /**
     * Execute a stored procedure.
     */
    public function executeProcedure(string $procedure, array $bindings = [])
    {
        return $this->query()->procedure($procedure, $bindings)->get();
    }

    /**
     * Escape a boolean value for Firebird.
     *
     * Uses 0/1 for cross-version compatibility.
     * FB 3.0+ Dialect 3 supports TRUE/FALSE but 0/1 works everywhere.
     */
    protected function escapeBool($value)
    {
        return $value ? '1' : '0';
    }

    /**
     * Escape a binary value for Firebird.
     */
    protected function escapeBinary($value)
    {
        $hex = bin2hex($value);

        return "x'{$hex}'";
    }

    /**
     * Determine if the given exception is a unique constraint error.
     */
    protected function isUniqueConstraintError(\Exception $exception)
    {
        return str_contains($exception->getMessage(), 'violation of PRIMARY or UNIQUE KEY constraint')
            || str_contains($exception->getMessage(), '-803');
    }

    /**
     * Parse the constraint name and columns from a unique constraint violation exception.
     */
    protected function parseUniqueConstraintViolation(\Exception $exception): array
    {
        $index = null;
        $columns = [];

        if (preg_match('/constraint "([^"]+)"/', $exception->getMessage(), $matches)) {
            $index = $matches[1];
        }

        if (preg_match_all('/"([^"]+)"\s*=/', $exception->getMessage(), $colMatches)) {
            $columns = $colMatches[1];
        }

        return ['index' => $index, 'columns' => $columns];
    }
}
