name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.5, 8.4, 8.3, 8.2]
        laravel: [12.*]
        stability: [prefer-lowest, prefer-stable]
        firebird: [5, 4]
        phpunit: [12.*]
        include:
          - laravel: 12.*
            testbench: ^10.0
          - php: 8.2
            phpunit: 11.*
        exclude:
          - php: 8.2
            phpunit: 12.*
      fail-fast: false

    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, Firebird ${{ matrix.firebird }}, ${{ matrix.stability }}

    services:
      firebird:
        image: firebirdsql/firebird:${{ matrix.firebird }}
        env:
          FIREBIRD_DATABASE: "database.fdb"
          FIREBIRD_ROOT_PASSWORD: "masterkey"
          FIREBIRD_USE_LEGACY_AUTH: "true"
        ports:
          - 3050:3050

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo_firebird
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit
